steps:
  # Node version display
  - name: node:14
    id: Check node version
    entrypoint: node
    args: ["--version"]
  # Npm version display
  - name: node:14
    id: Check npm version
    entrypoint: npm
    args: ["--version"]
