steps:
  ###Build App###
  # 6 Python version display
  - name: python
    id: Python Version check
    entrypoint: python3
    args: ["--version"]
  # 4 Displaying Google Id
  - id: Setup Google Project ID
    name: "ubuntu"
    entrypoint: bash
    env:
      - "GCLOUD_SERVICE_KEY=${_SERVICE_ACCOUNT}"
      - "project_name=${PROJECT_ID}"
      # - 'GOOGLE_PROJECT_ID=${!project_name}'
    args:
      - -c
      - |
        if [[ "$BRANCH_NAME" == "develop" ]]
        then
          echo "Development stuff only"
        elif [[ "$BRANCH_NAME" == "main" ]]
        then
          echo "Production stuff only"
        fi
  # 5 Storing service account key
  - name: "ubuntu"
    entrypoint: bash
    id: Store Service Account
    args:
      - -c
      - |
        echo ${!GCLOUD_SERVICE_KEY} | base64 --decode --ignore-garbage > /workspace/gcloud-service-key.json
