steps:
# - id: build-app
#   name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:404.0.0'
#   args: []
- id: build-hosting
  name: node
  entrypoint: yarn
  args: ['install', '--production=false', '--force']
- id: build-functions
  name: 'node:14.20.0'
- id: build-app
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:404.0.0'
- id: build-dataflow
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  waitFor: ["-"]
- id: deploy-hosting
  name: 'node:14.20.0'
  waitFor: [ build-hosting, build-functions, build-dataflow, build-app ]
- id: deploy-functions
  name: 'node:14.20.0'
  waitFor: [ build-hosting, build-functions, build-dataflow, build-app ]
- id: deploy-dataflow
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  waitFor: [ build-hosting, build-functions, build-dataflow, build-app ]
- id: deploy-app
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:404.0.0'
  waitFor: [ build-hosting, build-functions, build-dataflow, build-app ]
- id: deploy-workflows
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  waitFor: [ build-hosting, build-functions, build-dataflow, build-app ]
- id: notify
  name: 'node:10.17.0'
  waitFor: [ deploy-hosting, deploy-dataflow, deploy-functions, deploy-app ]
- id: release
  name: 'node:9.5'
  waitFor: [ deploy-hosting, deploy-dataflow, deploy-functions, deploy-app ]
