steps:
  ###Build App###
  # 6 Python version display
  - name: python
    id: Python Version check
    entrypoint: python3
    args: ["--version"]
  - name: node
    id: Check npm version
    entrypoint: npm
    args: ["--version"]
  # 4 Displaying Google Id
  - id: Setup Google Project ID
    name: "bash"
    entrypoint: bash
    args:
      - -c
      - |
        if [[ "$BRANCH_NAME" == "develop" ]]
        then
          echo "Development stuff only"
          steps:
            - name: python
              id: Python Version check
              entrypoint: python3
              args: ["--version"]
        elif [[ "$BRANCH_NAME" == "main" ]]
        then
          echo "Production stuff only"
        fi
