steps:
  - id: "Stop Other Ongoing Build"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - -c
      - |
        on_going_build=($(gcloud builds list --ongoing --format='value(id)' --filter="substitutions.TRIGGER_NAME=$TRIGGER_NAME" | xargs))
        for (( i=0; i<${#on_going_build[@]}; i++ )); do
          if [ "$i" -gt "0" ]; then # skip current
            echo "Cancelling build ${on_going_build[i]}"

            gcloud builds cancel ${on_going_build[i]}
          fi
        done
  - id: Branch Filtering Testing
    name: node
    entrypoint: bash
    args:
      - -c
      - |
        if [[ "$BRANCH_NAME" == "delta" || "$BRANCH_NAME" == "development" || "$BRANCH_NAME" == "epsilon" || "$BRANCH_NAME" == "staging" ]]
        then
          echo "Main Branch stuff only"
          yarn
        elif [[ "$BRANCH_NAME" == "develop" ]]
        then
          echo "TESTING FIREBASE DEPLOYMENTS ${PROJECT_ID}"
          echo "sub-branch stuff only"
        fi
  - name: gcr.io/${PROJECT_ID}/firebase
    id: Get Firebase Config
    entrypoint: firebase
    args:
      - -c
        - |
        if [[ "$BRANCH_NAME" == "delta" || "$BRANCH_NAME" == "develop" || "$BRANCH_NAME" == "epsilon" || "$BRANCH_NAME" == "staging" ]]
        then
        firebase use ${PROJECT_ID}
        fi
