steps:
  ###Build App###
  - name: node
    id: Check npm version
    entrypoint: npm
    args: ["--version"]
  # 4 Displaying Google Id
  - id: Setup Google Project ID
    name: "node"
    entrypoint: bash
    args:
      - -c
      - |
        if [[ "$BRANCH_NAME" == "develop" ]]
        then
          echo "Development stuff only"
          yarn
          yarn run
        elif [[ "$BRANCH_NAME" == "main" ]]
        then
          echo "Production stuff only"
        fi
